name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug API Token
        run: echo "API token is ${{ secrets.HEROKU_API_TOKEN }}"

      - name: Debug App Name
        run: echo "App name is ${{ secrets.HEROKU_APP_NAME }}"

      - name: Deploy to Heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master
